# SEO settings
title: "dev."
title2: "10thacb.com"
description: "J-6 Shop"
keywords: ""
url: https://dev.10thacb.com/
baseurl: null
comments: false

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
